version: 2

models:
  - name: stg_addresses
    description: customer addresses
  - name: stg_users
    description: customer info
  - name: stg_events
    description: web events
  - name: stg_orders
    description: all order
  - name: stg_order_items
    description: individual order items + quantity
  - name: stg_products
    description: product info
  - name: stg_promos
    description: discounts application
    
    