version: 2

models:

  - name: p_fact_products
    description: fact order view. This ties together all user, address, promo and products infomration related to orders.
    columns:
      - name: product_id
        descriptiodbn: unique order identifier
        tests:
          - not_null
          
  - name: p_fact_productconversionrate
    description: Product Viewed to Product Purchased conversion rates per product.
    columns:
      - name: product_id
        description: unique order identifier
        tests:
          - not_null


